channels:
- conda-forge
dependencies:
- python=3.11.10
- pip<=24.2
- pip:
  - mlflow==2.19.0
  - cloudpickle==3.1.1
  - numpy==2.1.2
  - pandas==2.2.3
  - psutil==6.1.0
  - scikit-learn==1.5.0
  - scipy==1.15.1
  - xgboost==2.1.3
name: mlflow-env
