name: Azure CI P7 Pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (e.g., dev, prod)'
        required: true
        default: 'dev'
      model_path:
        description: 'Path to the MLflow model'
        required: true
        default: 'mlflow_model/'  # Default path

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --user -r requirements.txt
        pip install azureml-sdk mlflow

    - name: Run tests
      run: |
        pytest pytest_tests.py --cov=pipeline --cov-report=xml

    # Log the model_path input
    - name: Log Model Path
      run: |
        echo "Model Path: ${{ github.event.inputs.model_path }}"

    # List the files in the model path directory to verify if the model is there
    - name: List files in model path
      run: |
        ls -R ${{ github.event.inputs.model_path }}

    - name: Authenticate with Azure
      run: |
        az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
        az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        az account show  # Check authentication success

    - name: Install Azure ML CLI extension
      run: |
        az extension add --name azure-cli-ml

    - name: Deploy Model to Azure ML
      if: success()  # Execute only if tests succeed
      run: |
        # Register the MLflow model in Azure ML
        az ml model register --name P7-mlflow-model \
            --model-path ${{ github.event.inputs.model_path }}/model.pkl \
            --workspace-name P7_Scoring \
            --resource-group Maud
        
        # Deploy the model to ACI
        az ml model deploy --name P7-mlflow-endpoint \
            --model P7-mlflow-model:1 \
            --workspace-name P7_Scoring \
            --resource-group Maud \
            --aci --no-wait

        # Optionally check the status of the deployed service
        az ml webservice show --name P7-mlflow-endpoint --workspace-name P7_Scoring --resource-group Maud